version: '3.9'

services:

  social_php:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: social_php
    volumes:
      - ${SOCIAL_DOCKER_APP_PATH}:/var/www:rw
#    depends_on:
#      - users_postgres
    networks:
      - social-network

  social_nginx:
    container_name: social_nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    environment:
      FPM_HOST: ${SOCIAL_FPM_HOST}
      SERVER_NAME: ${SOCIAL_SERVER_NAME}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${SOCIAL_DOCKER_APP_PATH}:/var/www:rw
    depends_on:
      - social_php
    networks:
      - social-network


  social_arangodb:
    container_name: social_arangodb
    hostname: social_arangodb
    build:
      context: ./arangodb
      dockerfile: Dockerfile
    volumes:
      - social-storage:/var/lib/arangodb3
    environment:
      ARANGO_ROOT_PASSWORD: root
    ports:
      - "8529:8529"
    networks:
      - social-network

volumes:
  social-storage:
    name: social-storage
    driver: local

#Docker Networks
networks:
  social-network:
    driver: bridge




